### ISSUE TITLE
load_data.md missing information

### ISSUE THREAD

**Issue by zawadzkia** [liquibase/liquibase.github.com#143]
"When specified target table contains column of TEXT type, then corresponding csv column have to contain path to existing file with data which will be loaded. In this case
each value entered in corresponding csv column is treated as path to file."

I think this info is missing in file load_data.md

Also, if user is not aware of this and will enter simple text instead of path, then null pointer exception is occurring without any meaningful information what causing the problem.

**Comment by r2datical** [comment]
Thanks! How should we fix this, @zawadzkia?

**Comment by nniesen** [comment]
All of the .md files in `/documention/changes` are generated by the `ChangeDocGenerator` in `_doc_generators` so any changes would need to be made in: 
https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/change/core/LoadDataChange.java

This an many other issues for the Changes and Refactorings may likely be fixed by running the `gradlew generateChangesDoc` tool that was in PR 181 and committing the updated directory: https://github.com/liquibase/liquibase.github.com/pull/181

**Comment by r2liquibase** [comment]
@zawadzkia Let us know if you would like to discuss. Simply reopen the issue.
