### ISSUE TITLE
The Changes/Refactorings documentation no longer displays

### ISSUE THREAD

**Issue by nniesen** [liquibase/liquibase.github.com#185]
The Changes/Refactorings documentation no longer displays when the link are clicked.

![image](https://user-images.githubusercontent.com/4194475/65469578-8fdc8800-de2d-11e9-93ee-f8b2bb840fad.png)

Instead this page is shown with information about extensions but no information about the built-in changes and refactorings:
![image](https://user-images.githubusercontent.com/4194475/65469690-ea75e400-de2d-11e9-9597-a1908e3d5a32.png)

**Comment by tabuckner** [comment]
@nniesen I've gone back to a commit from 8/10 and I'm still seeing the same as what you've shown above. What's the expected behavior, and maybe you can help us track down a commit that shows the expected behavior?

Reference Commit:
https://github.com/liquibase/liquibase.github.com/commit/4e27dcdf41bd164fd1aa9d01911249d71556927d

**Comment by nniesen** [comment]
@tabuckner Sorry, I'm being an idiot! I was on a small screen and didn't see them showing in the nav panel but scrolled off of the screen. I haven't had the opportunity to use Liquibase for a year and was expecting the nav panel to expand with the sub-navs indented.
